import { ContactResult } from './types';

export const mockResults: ContactResult[] = [
  {
    id: '1',
    businessName: 'Sunrise Digital Marketing',
    email: 'contact@sunrisedigital.com',
    phone: '+1 (555) 234-5678',
    website: 'https://sunrisedigital.com',
    address: '123 Market St, San Francisco, CA 94105',
    source: 'meta',
    category: 'Marketing Agency',
    rating: 4.8,
    reviews: 142,
    verified: true,
    lastUpdated: '2026-01-15',
  },
  {
    id: '2',
    businessName: 'Blue Ocean Restaurant',
    email: 'info@blueoceanrestaurant.com',
    phone: '+1 (555) 876-5432',
    website: 'https://blueoceanrestaurant.com',
    address: '456 Ocean Ave, Los Angeles, CA 90001',
    source: 'google_maps',
    category: 'Restaurant',
    rating: 4.5,
    reviews: 892,
    verified: true,
    lastUpdated: '2026-01-14',
  },
  {
    id: '3',
    businessName: 'TechFlow Solutions',
    email: 'hello@techflowsolutions.io',
    phone: '+1 (555) 111-2233',
    website: 'https://techflowsolutions.io',
    address: '789 Innovation Blvd, Austin, TX 78701',
    source: 'google_my_business',
    category: 'IT Services',
    rating: 4.9,
    reviews: 67,
    verified: true,
    lastUpdated: '2026-01-13',
  },
  {
    id: '4',
    businessName: 'Green Leaf Landscaping',
    email: 'services@greenleaflandscaping.com',
    phone: '+1 (555) 444-5566',
    website: 'https://greenleaflandscaping.com',
    address: '321 Garden Rd, Portland, OR 97201',
    source: 'meta',
    category: 'Landscaping',
    rating: 4.3,
    reviews: 56,
    verified: false,
    lastUpdated: '2026-01-12',
  },
  {
    id: '5',
    businessName: 'Peak Fitness Studio',
    email: 'join@peakfitnessstudio.com',
    phone: '+1 (555) 777-8899',
    website: 'https://peakfitnessstudio.com',
    address: '555 Health Way, Denver, CO 80201',
    source: 'google_maps',
    category: 'Fitness Center',
    rating: 4.7,
    reviews: 234,
    verified: true,
    lastUpdated: '2026-01-11',
  },
  {
    id: '6',
    businessName: 'Artisan Coffee Roasters',
    email: 'orders@artisancoffee.co',
    phone: '+1 (555) 333-4455',
    website: 'https://artisancoffee.co',
    address: '88 Bean St, Seattle, WA 98101',
    source: 'google_my_business',
    category: 'Coffee Shop',
    rating: 4.6,
    reviews: 445,
    verified: true,
    lastUpdated: '2026-01-10',
  },
  {
    id: '7',
    businessName: 'CloudNine Legal Services',
    email: 'intake@cloudninelegal.com',
    phone: '+1 (555) 999-0011',
    website: 'https://cloudninelegal.com',
    address: '200 Justice Ave, New York, NY 10001',
    source: 'meta',
    category: 'Legal Services',
    rating: 4.4,
    reviews: 89,
    verified: true,
    lastUpdated: '2026-01-09',
  },
  {
    id: '8',
    businessName: 'Fresh Bloom Florist',
    email: 'bouquets@freshbloomflorist.com',
    phone: '+1 (555) 222-3344',
    website: 'https://freshbloomflorist.com',
    address: '42 Petal Lane, Miami, FL 33101',
    source: 'google_maps',
    category: 'Florist',
    rating: 4.8,
    reviews: 178,
    verified: false,
    lastUpdated: '2026-01-08',
  },
  {
    id: '9',
    businessName: 'Metro Auto Repair',
    email: 'service@metroautorepair.com',
    phone: '+1 (555) 666-7788',
    website: 'https://metroautorepair.com',
    address: '900 Motor Dr, Chicago, IL 60601',
    source: 'google_my_business',
    category: 'Auto Repair',
    rating: 4.2,
    reviews: 312,
    verified: true,
    lastUpdated: '2026-01-07',
  },
  {
    id: '10',
    businessName: 'Harmony Yoga & Wellness',
    email: 'namaste@harmonyyoga.com',
    phone: '+1 (555) 555-1234',
    website: 'https://harmonyyoga.com',
    address: '77 Zen Blvd, Boulder, CO 80301',
    source: 'meta',
    category: 'Yoga Studio',
    rating: 4.9,
    reviews: 203,
    verified: true,
    lastUpdated: '2026-01-06',
  },
  {
    id: '11',
    businessName: 'Trendy Threads Boutique',
    email: 'hello@trendythreads.co',
    phone: '+1 (555) 888-9900',
    website: 'https://trendythreads.co',
    address: '150 Fashion Ave, New York, NY 10001',
    source: 'tiktok',
    category: 'Fashion Retail',
    rating: 4.7,
    reviews: 156,
    verified: true,
    lastUpdated: '2026-01-16',
  },
  {
    id: '12',
    businessName: 'FitLife Supplements',
    email: 'support@fitlifesupplements.com',
    phone: '+1 (555) 444-7788',
    website: 'https://fitlifesupplements.com',
    address: '88 Health St, Los Angeles, CA 90001',
    source: 'tiktok',
    category: 'Health & Fitness',
    rating: 4.6,
    reviews: 234,
    verified: true,
    lastUpdated: '2026-01-15',
  },
  {
    id: '13',
    businessName: 'Cosmic Beauty Studio',
    email: 'book@cosmicbeauty.com',
    phone: '+1 (555) 333-6677',
    website: 'https://cosmicbeauty.com',
    address: '222 Glamour Blvd, Miami, FL 33101',
    source: 'tiktok',
    category: 'Beauty Salon',
    rating: 4.8,
    reviews: 189,
    verified: false,
    lastUpdated: '2026-01-14',
  },
];
